#these numbers are arbitrary and can be changed
import math

import cv2

import ctypes
user32 = ctypes.windll.user32
user32.SetProcessDPIAware()
[MONITOR_WIDTH, MONITOR_HEIGHT] = [user32.GetSystemMetrics(0), user32.GetSystemMetrics(1)]

WINDOW_WIDTH = MONITOR_WIDTH * 1800//2560
WINDOW_HEIGHT = MONITOR_HEIGHT * 1300//1440

MAIN_FRAME_WIDTH = MONITOR_WIDTH * 900//2560
MAIN_FRAME_HEIGHT = MONITOR_HEIGHT * 450//1440

WARPED_FRAME_WIDTH = MONITOR_WIDTH * 600//2560
WARPED_FRAME_HEIGHT = MONITOR_HEIGHT * 1200//1440

FONT = cv2.FONT_HERSHEY_SIMPLEX

MENU_BAR_HEIGHT = MONITOR_HEIGHT*30//1440
LEFT_MARGIN = MONITOR_WIDTH * 20//2560

POCKET_RADIUS = math.floor(math.sqrt(WARPED_FRAME_WIDTH*WARPED_FRAME_HEIGHT*0.007/math.pi)) #keeps radius a consistant across varying screen sizes

WARPED_FRAME_POCKETS = [(POCKET_RADIUS, POCKET_RADIUS), (WARPED_FRAME_WIDTH-POCKET_RADIUS, POCKET_RADIUS), (POCKET_RADIUS//2, WARPED_FRAME_HEIGHT // 2), (WARPED_FRAME_WIDTH-POCKET_RADIUS//2, WARPED_FRAME_HEIGHT // 2), (POCKET_RADIUS, WARPED_FRAME_HEIGHT-POCKET_RADIUS), (WARPED_FRAME_WIDTH-POCKET_RADIUS, WARPED_FRAME_HEIGHT-POCKET_RADIUS)]


CUE_STRIPE_THRESHOLD = 1.0
STRIPE_SOLID_THRESHOLD = .25
EIGHT_THRESHOLD = .8


BALL_TYPE_UNKNOWN = 0
BALL_TYPE_SOLID = 1
BALL_TYPE_STRIPE = 2
BALL_TYPE_EIGHT = 3
BALL_TYPE_CUE = 4
FIRST_BALL = 5
NON_FIRST_BALL = 6

